spring:
  #数据来源库
  source:
    url: jdbc:mysql://127.0.0.1:3306/zgdc_services?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    #目标数据库
  target:
    url: jdbc:postgresql://127.0.0.1:5432/zgdc_warehouse_source?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: postgres
    password: 123456
    # 需要传输的表
  trasform:
    tables: new_year_county_person_distribute