spring:
  #数据来源库
  source:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/dinner?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: bigdata
    password: cdzg123!@#
    #目标数据库
  target:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://test-mysql:11007/warehouse_source?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: ZGdc@2019
    # 需要传输的表
  trasform:
    tables: t_order_meal,t_revenue_info